version: "3"
services:
  reverseproxy:
      image: zhangyhgg/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: zhangyhgg/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: mydbmydb
      POSTGRESS_PASSWORD: mydbmydb 
      POSTGRESS_DB: template1 
      POSTGRESS_HOST: mydbmydb.cxmmfrmwbxdh.us-east-1.rds.amazonaws.com
      POSTGRESS_DIALECT: postgres 
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: imagebucket-zhang-dev
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  backend-feed:
    image: zhangyhgg/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: mydbmydb
      POSTGRESS_PASSWORD: mydbmydb 
      POSTGRESS_DB: template1 
      POSTGRESS_HOST: mydbmydb.cxmmfrmwbxdh.us-east-1.rds.amazonaws.com
      POSTGRESS_DIALECT: postgres 
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: imagebucket-zhang-dev
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  frontend:
    image: zhangyhgg/udacity-frontend:local
    ports:
      - "8100:80"
